version: '2'
services:
  logspout:
    image: bekt/logspout-logstash
    restart: always
    network_mode: host
    environment:
      - ROUTE_URIS=logstash://localhost:5000
      - EXCLUDE_LABEL=logspout.exclude
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
  logstash:
    image:
